### ISSUE TITLE
Availability of data before April 1st 2020?

### ISSUE THREAD

**Issue by edomt** [YouGov-Data/covid-19-tracker#4]
Hi! First, thank you very much for publishing this data! We're looking into how we could make it available as part of our COVID-19 data visualizations on [ourworldindata.org](https://ourworldindata.org/coronavirus).

All the data located in https://github.com/YouGov-Data/covid-19-tracker/tree/master/data starts on April 1st 2020, but most charts visible on yougov.co.uk seem to start a bit earlier, around late February/early March. Is there a particular reason why this earlier data is not part of the CSV files in this repo? And if not, would it be possible to upload it here?

Thank you!
Edouard

**Comment by jackobailey** [comment]
It would also be useful for my own purposes if we could get the earlier data too!

**Comment by GavinEllison** [comment]
Hi
The data on the YouGov website isn't the same study as this one. That data was collected ad-hoc from local YouGov office through questions posted on a number of different surveys, from early 2020. It isn't possible to collate that as respondents level data. The data provided here is from a joint study with Imperial College which began in later March, early April 2020 where the decision was made to collate that data in this form and share it. 
Gavin

**Comment by jackobailey** [comment]
Thanks for clearing that up, Gavin
