### ISSUE TITLE
Error in france.csv since June 15 update

### ISSUE THREAD

**Issue by bnjmacdonald** [YouGov-Data/covid-19-tracker#5]
Commit eff3fed0a083a4b22ca79245fb8b3b5600b1fdcc erroneously shifted rows one column to the right (from at least the `i12_health_27` column onwards) in `france.csv` for week 33 (`RecordNo` 32370+).

<img width="1675" alt="Screen Shot 2021-06-22 at 12 09 44 PM" src="https://user-images.githubusercontent.com/11767602/122950887-359a8f00-d353-11eb-884b-b13a9f2a65d5.png">

**Comment by GavinEllison** [comment]
Thanks, the latest update has corrected that.
